
import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import Layout from '@/components/Layout';
import { Image, FileText, Video, AudioLines } from 'lucide-react';
import { cn } from '@/lib/utils';

const Index = () => {
  // Feature animation with entry delay
  useEffect(() => {
    const features = document.querySelectorAll('.feature-card');
    features.forEach((feature, index) => {
      setTimeout(() => {
        feature.classList.add('animate-enter');
        feature.classList.remove('opacity-0');
      }, 300 + index * 150);
    });
  }, []);

  const features = [
    {
      title: "Image Detection",
      description: "Detect AI-generated images with advanced neural networks",
      icon: Image,
      color: "from-blue-500 to-cyan-400",
      link: "/image"
    },
    {
      title: "Video Analysis",
      description: "Identify synthetic videos and deepfakes with frame analysis",
      icon: Video,
      color: "from-purple-500 to-pink-500",
      link: "/video"
    },
    {
      title: "Audio Recognition",
      description: "Distinguish between AI and human-generated audio content",
      icon: AudioLines,
      color: "from-amber-500 to-orange-500",
      link: "/audio"
    },
    {
      title: "Text Verification",
      description: "Analyze text to detect content generated by language models",
      icon: FileText,
      color: "from-green-500 to-emerald-400",
      link: "/text"
    }
  ];

  return (
    <Layout>
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent z-0"></div>
        <div className="container mx-auto px-4 py-20 md:py-32 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-6 animate-fade-in">
              <span className="gradient-text">AuraGuardian</span>
            </h1>
            <p className="text-xl md:text-2xl mb-8 text-muted-foreground animate-fade-in" style={{ animationDelay: '0.2s' }}>
              Advanced multimodal AI-generated content detection system
            </p>
            <p className="text-lg mb-10 animate-fade-in" style={{ animationDelay: '0.3s' }}>
              Detect AI-generated images, videos, audio, and text with high accuracy using our cutting-edge neural networks
            </p>
            <div className="flex flex-wrap justify-center gap-4 animate-fade-in" style={{ animationDelay: '0.4s' }}>
              <Button asChild size="lg">
                <Link to="/image">Get Started</Link>
              </Button>
              <Button variant="outline" size="lg">
                Learn More
              </Button>
            </div>
          </div>

          {/* Abstract Graphics/Decorations */}
          <div className="absolute left-10 top-40 w-20 h-20 rounded-full bg-gradient-to-r from-blue-500/20 to-purple-500/20 blur-xl animate-float" style={{ animationDelay: '0.5s' }}></div>
          <div className="absolute right-20 bottom-20 w-32 h-32 rounded-full bg-gradient-to-r from-pink-500/20 to-orange-500/20 blur-xl animate-float" style={{ animationDelay: '1.5s' }}></div>
          <div className="absolute left-1/3 bottom-10 w-16 h-16 rounded-full bg-gradient-to-r from-green-500/20 to-cyan-500/20 blur-xl animate-float" style={{ animationDelay: '1s' }}></div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-16 md:py-24">
        <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">Detection Capabilities</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-5xl mx-auto">
          {features.map((feature, index) => (
            <Card key={index} className="feature-card opacity-0 interactive-card border overflow-hidden">
              <CardHeader className={cn("border-b", `bg-gradient-to-r ${feature.color} bg-clip-text text-transparent`)}>
                <div className="flex items-center mb-2">
                  <feature.icon className="h-6 w-6 mr-2" />
                  <CardTitle>{feature.title}</CardTitle>
                </div>
                <CardDescription>{feature.description}</CardDescription>
              </CardHeader>
              <CardContent className="pt-6 pb-4 flex justify-end">
                <Button variant="ghost" asChild>
                  <Link to={feature.link}>Try Now</Link>
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* How It Works Section */}
      <section className="bg-muted/50 py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">How It Works</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            <div className="bg-white dark:bg-black/20 p-6 rounded-lg shadow-sm text-center">
              <div className="w-12 h-12 rounded-full bg-primary/10 text-primary flex items-center justify-center mx-auto mb-4">
                <span className="text-lg font-bold">1</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Upload Content</h3>
              <p className="text-muted-foreground">
                Upload your media file or paste your text that you want to analyze
              </p>
            </div>
            
            <div className="bg-white dark:bg-black/20 p-6 rounded-lg shadow-sm text-center">
              <div className="w-12 h-12 rounded-full bg-primary/10 text-primary flex items-center justify-center mx-auto mb-4">
                <span className="text-lg font-bold">2</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Advanced Analysis</h3>
              <p className="text-muted-foreground">
                Our specialized neural networks analyze the content for AI signatures
              </p>
            </div>
            
            <div className="bg-white dark:bg-black/20 p-6 rounded-lg shadow-sm text-center">
              <div className="w-12 h-12 rounded-full bg-primary/10 text-primary flex items-center justify-center mx-auto mb-4">
                <span className="text-lg font-bold">3</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Get Results</h3>
              <p className="text-muted-foreground">
                Receive a detailed report on whether the content is AI-generated or authentic
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 py-16 md:py-24 text-center">
        <h2 className="text-3xl md:text-4xl font-bold mb-6">Ready to identify AI-generated content?</h2>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Start using our advanced detection system today to verify the authenticity of digital content.
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <Button asChild size="lg" variant="default" className="animate-pulse-glow">
            <Link to="/image">Try Image Detection</Link>
          </Button>
          <Button asChild size="lg" variant="outline">
            <Link to="/text">Try Text Detection</Link>
          </Button>
        </div>
      </section>
    </Layout>
  );
};

export default Index;
